### ISSUE TITLE
filegen does not compile

### ISSUE THREAD

**Issue by danielrainer** [PeterTh/perf-oriented-dev#1]
The `filegen` program does not compile using GCC 12.2.1.

The following warnings are generated (and treated as errors due to `-Werror`) when following the compilation instructions in `small_sample/README.md` (absolute paths shortened):

```text
[2/12] Building C object CMakeFiles/filegen.dir/filegen/filegen.c.o
FAILED: CMakeFiles/filegen.dir/filegen/filegen.c.o 
/usr/bin/cc   -O3 -DNDEBUG -Wall -Wextra -Wpedantic -Werror -MD -MT CMakeFiles/filegen.dir/filegen/filegen.c.o -MF CMakeFiles/filegen.dir/filegen/filegen.c.o.d -o CMakeFiles/filegen.dir/filegen/filegen.c.o -c ~/perf-oriented-dev/small_samples/filegen/filegen.c
~/perf-oriented-dev/small_samples/filegen/filegen.c: In function ‘main’:
~/perf-oriented-dev/small_samples/filegen/filegen.c:57:20: error: this statement may fall through [-Werror=implicit-fallthrough=]
   57 |             seed = atoi(argv[5]);
      |                    ^~~~~~~~~~~~~
~/perf-oriented-dev/small_samples/filegen/filegen.c:58:9: note: here
   58 |         case 5:
      |         ^~~~
~/perf-oriented-dev/small_samples/filegen/filegen.c: In function ‘create_files’:
~/perf-oriented-dev/small_samples/filegen/filegen.c:30:52: error: ‘/file_’ directive output may be truncated writing 6 bytes into a region of size between 1 and 256 [-Werror=format-truncation=]
   30 |         snprintf(filename, MAX_FILENAME_LENGTH, "%s/file_%d", full_dirname, j);
      |                                                    ^~~~~~
~/perf-oriented-dev/small_samples/filegen/filegen.c:30:49: note: directive argument in the range [0, 2147483646]
   30 |         snprintf(filename, MAX_FILENAME_LENGTH, "%s/file_%d", full_dirname, j);
      |                                                 ^~~~~~~~~~~~
~/perf-oriented-dev/small_samples/filegen/filegen.c:30:9: note: ‘snprintf’ output between 8 and 272 bytes into a destination of size 256
   30 |         snprintf(filename, MAX_FILENAME_LENGTH, "%s/file_%d", full_dirname, j);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
[7/12] Building C object CMakeFiles/delannoy.dir/delannoy/delannoy.c.o
ninja: build stopped: subcommand failed.

```

**Comment by PeterTh** [comment]
Thanks, should be fixed with 5935fba.

How to create a debug build on LCC2:
```
module load gcc/12.2.0-gcc-4.8.5-ykbdn5t
module load cmake/3.24.3-gcc-12.2.0-lljyybc
module load ninja/1.11.1-python-3.10.8-gcc-12.2.0-g4jxnoc
cd perf-oriented-dev/small_samples
mkdir build_dbg
cd build_dbg
cmake -DCMAKE_BUILD_TYPE=Debug -G Ninja ..
ninja
```
